# Generated by Django 5.0.7 on 2024-10-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='account_no',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
