# Generated by Django 5.0.7 on 2024-10-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userbankaccount_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
